### ISSUE TITLE
SPICE_F_NONBLOCK not defined

### ISSUE THREAD

**Issue by tcr** [stemjail/fd-rs#1]
Issue with a non x86_64 system on this line:

https://github.com/stemjail/fd-rs/blob/524bba1f778c4b7af1965aa162981996f6b3d662/src/splice.rs#L51

On a non x86_64 system, the constant isn't defined, and you'll get the following error:

```
error[E0425]: unresolved name `raw::SPLICE_F_NONBLOCK`
  --> /Users/tim/.cargo/registry/src/github.com-1ecc6299db9ec823/fd-0.2.2/src/splice.rs:51:33
   |
51 |         SpliceMode::NonBlock => raw::SPLICE_F_NONBLOCK,
   |                                 ^^^^^^^^^^^^^^^^^^^^^^

```

**Comment by l0kod** [comment]
I missed this issue. Yes, this value seems arch specific. Which arch do you use? What is the corresponding SPLICE_F_NONBLOCK?

**Comment by l0kod** [comment]
Well, I was over-restrictive, this command is architecture-agnostic. I will fix it. Thanks!
