### ISSUE TITLE
OSX 64bit failure building fd crate with recent libc versions.

### ISSUE THREAD

**Issue by gilescope** [stemjail/fd-rs#2]
Checking termios v0.2.2
    Checking fd v0.2.3
error[E0432]: unresolved import `libc::SPLICE_F_NONBLOCK`
  --> /Users/gilescope/.cargo/registry/src/github.com-1ecc6299db9ec823/fd-0.2.3/src/splice.rs:27:13
   |
27 |     pub use ::libc::SPLICE_F_NONBLOCK;
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^ no `SPLICE_F_NONBLOCK` in the root

error: aborting due to previous error

Steps to reproduce:

git clone https://github.com/stemjail/tty-rs.git
cd tty-rs
cargo build

I'm raising this as have seen this on a few different (tty) apps that all use fd as a dependency.
Looks like this is defined on only some OSes.

**Comment by gilescope** [comment]
(Not quite a dupe of #1) - mine is an issue with an x64 x86 system :-)

(I know the tty crates are a little dusty, but seems like this needs fixing before I can update them)

**Comment by l0kod** [comment]
`splice()` is a Linux-specific syscall, as are the related flags: https://github.com/rust-lang/libc/search?q=SPLICE_F_NONBLOCK

You can create a pull request to add a target_os check if you don't need the `splice_loop()` (and if the other features work on macOS), though. ;)
